Repository xmidt-org/scytale, pull requests merged in 2023-11, with the labels that each got.

#310 chore: update to wrpcontext.GetMessage
  WRPHandler.go
  go.mod
  go.sum
  primaryHandler.go
Labels: bug

#318 Wrp validation update
  primaryHandler.go
Labels: enhancement

#322 updated wrp-go to 3.2.3
  go.mod
  go.sum
Labels: bug, wrp validator
